"""Initial migration

Revision ID: 8ff51041db04
Revises: 
Create Date: 2024-11-29 11:14:27.786852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ff51041db04'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Adding length to String columns
    op.create_table('waste_collectors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(255), nullable=True),  # Added length
    sa.Column('contact_info', sa.String(255), nullable=True),  # Added length
    sa.Column('assigned_zone', sa.String(255), nullable=True),  # Added length
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_waste_collectors_assigned_zone'), 'waste_collectors', ['assigned_zone'], unique=False)
    op.create_index(op.f('ix_waste_collectors_contact_info'), 'waste_collectors', ['contact_info'], unique=False)
    op.create_index(op.f('ix_waste_collectors_id'), 'waste_collectors', ['id'], unique=False)
    op.create_index(op.f('ix_waste_collectors_name'), 'waste_collectors', ['name'], unique=False)
    
    op.create_table('waste_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(255), nullable=True),  # Added length
    sa.Column('description', sa.String(255), nullable=True),  # Added length
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('disposal_method', sa.String(255), nullable=True),  # Added length
    sa.Column('assigned_collector_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_collector_id'], ['waste_collectors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_waste_items_category'), 'waste_items', ['category'], unique=False)
    op.create_index(op.f('ix_waste_items_description'), 'waste_items', ['description'], unique=False)
    op.create_index(op.f('ix_waste_items_id'), 'waste_items', ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_waste_items_id'), table_name='waste_items')
    op.drop_index(op.f('ix_waste_items_description'), table_name='waste_items')
    op.drop_index(op.f('ix_waste_items_category'), table_name='waste_items')
    op.drop_table('waste_items')
    op.drop_index(op.f('ix_waste_collectors_name'), table_name='waste_collectors')
    op.drop_index(op.f('ix_waste_collectors_id'), table_name='waste_collectors')
    op.drop_index(op.f('ix_waste_collectors_contact_info'), table_name='waste_collectors')
    op.drop_index(op.f('ix_waste_collectors_assigned_zone'), table_name='waste_collectors')
    op.drop_table('waste_collectors')
    # ### end Alembic commands ###
